const PEOPLE=[
{id:"rachel",name:"Rachel Virginia Zahner",dates:"1983–Living",family:["Zahner","Downing","Blackwell"],relation:"Center generation",birth:"March 26, 1983",place:"Oklahoma City, Oklahoma",bio:"Rachel Virginia Zahner was born on March 26, 1983, in Oklahoma City, Oklahoma, to Gary Paul Zahner and Brenda Joyce Downing. She later built a family with Bradley Todd Blackwell, and together they have two sons, Brody and Vance."},
{id:"brad",name:"Bradley Todd Blackwell",dates:"1975–Living",family:["Blackwell","Barrett"],relation:"Spouse",birth:"May 26, 1975",place:"Missouri",bio:"Bradley Todd Blackwell was born on May 26, 1975, to John and Carol. He has one brother and one sister and later built a family with Rachel Virginia Zahner. Together they have two sons."},
{id:"brody",name:"Brody Paul Blackwell",dates:"2002–Living",family:["Blackwell","Zahner","Downing","Barrett"],relation:"Son",birth:"July 23, 2002",place:"Springfield, Greene County, Missouri",bio:"Brody Paul Blackwell was born on July 23, 2002, in Springfield, Missouri, to Rachel Virginia Zahner and Bradley Todd Blackwell."},
{id:"vance",name:"Vance Cully Blackwell",dates:"2005–Living",family:["Blackwell","Zahner","Downing","Barrett"],relation:"Son",birth:"April 27, 2005",place:"Branson, Taney County, Missouri",bio:"Vance Cully Blackwell was born on April 27, 2005, in Branson, Missouri, to Rachel Virginia Zahner and Bradley Todd Blackwell. He joined his older brother, Brody."},
{id:"gary",name:"Gary Paul Zahner",dates:"1953–Living",family:["Zahner"],relation:"Father of Rachel"},
{id:"brenda",name:"Brenda Joyce Downing",dates:"1955–Living",family:["Downing"],relation:"Mother of Rachel",birth:"December 17, 1955",place:"Illinois",bio:"Brenda Joyce Downing was born on December 17, 1955, in Illinois, to Claude Thomas Downing and Hazel Virginia Huey. She later had one daughter, Rachel Virginia Zahner, with Gary Paul Zahner. Brenda grew up among four brothers and five sisters."},
{id:"carol",name:"Carol Dean Barrett",dates:"1947–Living",family:["Barrett"],relation:"Mother of Bradley"},
{id:"johnjr",name:"John Smith Blackwell Jr.",dates:"1946–Deceased",family:["Blackwell"],relation:"Father of Bradley"},
{id:"johnsr",name:"John S. Blackwell Sr.",dates:"1914–1999",family:["Blackwell"],relation:"Grandfather"},
{id:"thomas",name:"Thomas Emory Blackwell",dates:"1870–1962",family:["Blackwell"],relation:"Earlier Blackwell ancestor"},
{id:"robert",name:"Robert Donald Zahner",dates:"1930–1989",family:["Zahner"],relation:"Grandfather"},
{id:"theodore",name:"Theodore Zahner",dates:"1889–1955",family:["Zahner"],relation:"Great-grandfather"},
{id:"claude",name:"Claude Thomas Downing",dates:"1931–1999",family:["Downing"],relation:"Grandfather"},
{id:"hazel",name:"Hazel Virginia Huey",dates:"1930–Deceased",family:["Downing"],relation:"Grandmother"},
{id:"wadowning",name:"W. A. Downing",dates:"Died 1975",family:["Downing"],relation:"Earlier Downing ancestor"},
{id:"billy",name:"Billy Barrett",dates:"1917–2009",family:["Barrett"],relation:"Grandfather"},
{id:"william",name:"William Iscca Barrett",dates:"1879–1930",family:["Barrett"],relation:"Earlier Barrett ancestor"}
];
const qs=new URLSearchParams(location.search),family=qs.get('family'),person=qs.get('person');
const nav=document.getElementById('nav'),menu=document.getElementById('menuBtn');if(menu)menu.addEventListener('click',()=>nav.classList.toggle('open'));
function card(p){return `<a class="person-card" href="person.html?person=${p.id}"><span class="badge">${p.family.join(' • ')}</span><h3>${p.name}</h3><p class="dates">${p.dates}</p><small>${p.relation||''}</small></a>`}
if(document.getElementById('familyTitle')){const rows=PEOPLE.filter(p=>p.family.includes(family||'Blackwell'));document.getElementById('familyTitle').textContent=(family||'Blackwell')+' Family';document.getElementById('familyLead').textContent='Living and deceased relatives appear together. Every person opens as a museum exhibit.';document.getElementById('familyPeople').innerHTML=rows.map(card).join('');document.getElementById('familyTimeline').href='timeline.html?family='+(family||'Blackwell');}
if(document.getElementById('personView')){const p=PEOPLE.find(x=>x.id===person)||PEOPLE[0];document.title=p.name+' — This Is What Happened';document.getElementById('personView').innerHTML=`<div class="person-head"><div class="portrait">Portrait<br>awaiting the family collection</div><div><p class="eyebrow">${p.family.join(' • ')} Family Tree</p><h2>${p.name}</h2><p class="lead">${p.dates}</p><span class="badge">${p.relation||'Family member'}</span></div></div><div class="museum-biography"><h3>Life Story</h3><p>${p.bio||p.name+' is part of the continuing family story. This exhibit will grow as photographs, records, places, and memories are connected.'}</p></div>${p.birth?`<div class="life-event"><div class="event-icon">✦</div><div><p class="eyebrow">Birth</p><h3>${p.birth}</h3><p>${p.place||'Place awaiting confirmation'}</p></div></div>`:''}<h3 class="section-title">Exhibit Cases</h3><div class="cards"><a class="card" href="gallery.html"><h3>Photographs</h3><p>Images connected to this person.</p></a><a class="card" href="archive.html"><h3>Documents</h3><p>Records connected to this life.</p></a><a class="card" href="timeline.html?family=${p.family[0]}"><h3>Timeline</h3><p>See this life in family context.</p></a><a class="card" href="add-a-discovery.html"><h3>Add a Discovery</h3><p>Contribute another piece of this story.</p></a></div>`;}
if(document.getElementById('timelineTitle')){const f=family||'Blackwell';document.getElementById('timelineTitle').textContent=f+' Family Timeline';const rows=PEOPLE.filter(p=>p.family.includes(f)).sort((a,b)=>(parseInt(a.dates)||9999)-(parseInt(b.dates)||9999));document.getElementById('timelineGrid').innerHTML=rows.map(card).join('');}
const input=document.getElementById('searchInput'),results=document.getElementById('results');if(input){const run=()=>{const q=input.value.trim().toLowerCase();results.innerHTML=q?PEOPLE.filter(p=>JSON.stringify(p).toLowerCase().includes(q)).map(card).join(''):'<p>Type a name, family, date, or place.</p>'};input.addEventListener('input',run);run();}
const form=document.getElementById('discoveryForm'),thanks=document.getElementById('discoveryThanks'),drawer=document.getElementById('curatorDrawer');if(form){const kindInput=document.getElementById('discoveryKind'),kindTitle=document.getElementById('selectedDrawerTitle');document.querySelectorAll('[data-kind]').forEach(button=>button.addEventListener('click',()=>{kindInput.value=button.dataset.kind;kindTitle.textContent=button.dataset.kind+' Drawer';drawer.hidden=true;form.hidden=false;form.scrollIntoView({behavior:'smooth',block:'start'});}));const back=document.getElementById('backToDrawer');if(back)back.addEventListener('click',()=>{form.reset();form.hidden=true;drawer.hidden=false;drawer.scrollIntoView({behavior:'smooth',block:'start'});});form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));const old=JSON.parse(localStorage.getItem('museumDiscoveries')||'[]');old.push({...data,saved:new Date().toISOString()});localStorage.setItem('museumDiscoveries',JSON.stringify(old));form.hidden=true;drawer.hidden=true;thanks.hidden=false;});document.getElementById('addAnother').addEventListener('click',()=>{form.reset();thanks.hidden=true;drawer.hidden=false;drawer.scrollIntoView({behavior:'smooth',block:'start'});});}
